export const ALL_EPATRIKA_GET_REQUEST = "ALL_EPATRIKA_GET_REQUEST";
export const ALL_EPATRIKA_GET_SUCCESS = "ALL_EPATRIKA_GET_SUCCESS";
export const ALL_EPATRIKA_GET_FAIL = "ALL_EPATRIKA_GET_FAIL";

export const EPATRIKA_DETAILS_GET_REQUEST = "EPATRIKA_DETAILS_GET_REQUEST";
export const EPATRIKA_DETAILS_GET_SUCCESS = "EPATRIKA_DETAILS_GET_SUCCESS";
export const EPATRIKA_DETAILS_GET_FAIL = "EPATRIKA_DETAILS_GET_FAIL";

export const EPATRIKA_CREATE_REQUEST = "EPATRIKA_CREATE_REQUEST";
export const EPATRIKA_CREATE_SUCCESS = "EPATRIKA_CREATE_SUCCESS";
export const EPATRIKA_CREATE_FAIL = "EPATRIKA_CREATE_FAIL";

export const EPATRIKA_UPDATE_REQUEST = "EPATRIKA_UPDATE_REQUEST";
export const EPATRIKA_UPDATE_SUCCESS = "EPATRIKA_UPDATE_SUCCESS";
export const EPATRIKA_UPDATE_FAIL = "EPATRIKA_UPDATE_FAIL";

export const EPATRIKA_DELETE_REQUEST = "EPATRIKA_DELETE_REQUEST";
export const EPATRIKA_DELETE_SUCCESS = "EPATRIKA_DELETE_SUCCESS";
export const EPATRIKA_DELETE_FAIL = "EPATRIKA_DELETE_FAIL";

export const EPATRIKA_CLEAR_ERRORS = "EPATRIKA_CLEAR_ERRORS";
