export const FAMILY_GET_REQUEST = "FAMILY_GET_REQUEST";
export const FAMILY_GET_SUCCESS = "FAMILY_GET_SUCCESS";
export const FAMILY_GET_FAIL = "FAMILY_GET_FAIL";

export const FAMILY_CREATE_REQUEST = "FAMILY_CREATE_REQUEST";
export const FAMILY_CREATE_SUCCESS = "FAMILY_CREATE_SUCCESS";
export const FAMILY_CREATE_FAIL = "FAMILY_CREATE_FAIL";

export const FAMILY_UPDATE_REQUEST = "FAMILY_UPDATE_REQUEST";
export const FAMILY_UPDATE_SUCCESS = "FAMILY_UPDATE_SUCCESS";
export const FAMILY_UPDATE_FAIL = "FAMILY_UPDATE_FAIL";

export const FAMILY_DELETE_REQUEST = "FAMILY_DELETE_REQUEST";
export const FAMILY_DELETE_SUCCESS = "FAMILY_DELETE_SUCCESS";
export const FAMILY_DELETE_FAIL = "FAMILY_DELETE_FAIL";

export const FAMILY_CLEAR_ERRORS = "FAMILY_CLEAR_ERRORS";