export const HOME_GET_REQUEST = "HOME_GET_REQUEST";
export const HOME_GET_SUCCESS = "HOME_GET_SUCCESS";
export const HOME_GET_FAIL = "HOME_GET_FAIL";

export const HOME_CREATE_REQUEST = "HOME_CREATE_REQUEST";
export const HOME_CREATE_SUCCESS = "HOME_CREATE_SUCCESS";
export const HOME_CREATE_FAIL = "HOME_CREATE_FAIL";

export const HOME_UPDATE_REQUEST = "HOME_UPDATE_REQUEST";
export const HOME_UPDATE_SUCCESS = "HOME_UPDATE_SUCCESS";
export const HOME_UPDATE_FAIL = "HOME_UPDATE_FAIL";

export const HOME_DELETE_REQUEST = "HOME_DELETE_REQUEST";
export const HOME_DELETE_SUCCESS = "HOME_DELETE_SUCCESS";
export const HOME_DELETE_FAIL = "HOME_DELETE_FAIL";

export const HOME_CLEAR_ERRORS = "HOME_CLEAR_ERRORS";