export const ALL_MARRIAGE_GET_REQUEST = "ALL_MARRIAGE_GET_REQUEST";
export const ALL_MARRIAGE_GET_SUCCESS = "ALL_MARRIAGE_GET_SUCCESS";
export const ALL_MARRIAGE_GET_FAIL = "ALL_MARRIAGE_GET_FAIL";


export const MARRIAGE_GET_DETAILS_REQUEST = "MARRIAGE_GET_DETAILS_REQUEST";
export const MARRIAGE_GET_DETAILS_SUCCESS = "MARRIAGE_GET_DETAILS_SUCCESS";
export const MARRIAGE_GET_DETAILS_FAIL = "MARRIAGE_GET_DETAILS_FAIL";

export const MARRIAGE_CREATE_REQUEST = "MARRIAGE_CREATE_REQUEST";
export const MARRIAGE_CREATE_SUCCESS = "MARRIAGE_CREATE_SUCCESS";
export const MARRIAGE_CREATE_FAIL = "MARRIAGE_CREATE_FAIL";

export const MARRIAGE_UPDATE_REQUEST = "MARRIAGE_UPDATE_REQUEST";
export const MARRIAGE_UPDATE_SUCCESS = "MARRIAGE_UPDATE_SUCCESS";
export const MARRIAGE_UPDATE_FAIL = "MARRIAGE_UPDATE_FAIL";

export const MARRIAGE_DELETE_REQUEST = "MARRIAGE_DELETE_REQUEST";
export const MARRIAGE_DELETE_SUCCESS = "MARRIAGE_DELETE_SUCCESS";
export const MARRIAGE_DELETE_FAIL = "MARRIAGE_DELETE_FAIL";

export const MARRIAGE_CLEAR_ERRORS = "MARRIAGE_CLEAR_ERRORS";

