export const ALL_NEWS_GET_REQUEST = "ALL_NEWS_GET_REQUEST";
export const ALL_NEWS_GET_SUCCESS = "ALL_NEWS_GET_SUCCESS";
export const ALL_NEWS_GET_FAIL = "ALL_NEWS_GET_FAIL";

export const NEWS_DETAILS_GET_REQUEST = "NEWS_DETAILS_GET_REQUEST";
export const NEWS_DETAILS_GET_SUCCESS = "NEWS_DETAILS_GET_SUCCESS";
export const NEWS_DETAILS_GET_FAIL = "NEWS_DETAILS_GET_FAIL";

export const NEWS_CREATE_REQUEST = "NEWS_CREATE_REQUEST";
export const NEWS_CREATE_SUCCESS = "NEWS_CREATE_SUCCESS";
export const NEWS_CREATE_FAIL = "NEWS_CREATE_FAIL";

export const NEWS_UPDATE_REQUEST = "NEWS_UPDATE_REQUEST";
export const NEWS_UPDATE_SUCCESS = "NEWS_UPDATE_SUCCESS";
export const NEWS_UPDATE_FAIL = "NEWS_UPDATE_FAIL";

export const NEWS_DELETE_REQUEST = "NEWS_DELETE_REQUEST";
export const NEWS_DELETE_SUCCESS = "NEWS_DELETE_SUCCESS";
export const NEWS_DELETE_FAIL = "NEWS_DELETE_FAIL";

export const NEWS_CLEAR_ERRORS = "NEWS_CLEAR_ERRORS";