export const PARVARIK_NIRDIKISHA_GET_REQUEST = "PARVARIK_NIRDIKISHA_GET_REQUEST";
export const PARVARIK_NIRDIKISHA_GET_SUCCESS = "PARVARIK_NIRDIKISHA_GET_SUCCESS";
export const PARVARIK_NIRDIKISHA_GET_FAIL = "PARVARIK_NIRDIKISHA_GET_FAIL";

export const PARVARIK_NIRDIKISHA_CREATE_REQUEST = "PARVARIK_NIRDIKISHA_CREATE_REQUEST";
export const PARVARIK_NIRDIKISHA_CREATE_SUCCESS = "PARVARIK_NIRDIKISHA_CREATE_SUCCESS";
export const PARVARIK_NIRDIKISHA_CREATE_FAIL = "PARVARIK_NIRDIKISHA_CREATE_FAIL";

export const PARVARIK_NIRDIKISHA_UPDATE_REQUEST = "PARVARIK_NIRDIKISHA_UPDATE_REQUEST";
export const PARVARIK_NIRDIKISHA_UPDATE_SUCCESS = "PARVARIK_NIRDIKISHA_UPDATE_SUCCESS";
export const PARVARIK_NIRDIKISHA_UPDATE_FAIL = "PARVARIK_NIRDIKISHA_UPDATE_FAIL";

export const PARVARIK_NIRDIKISHA_DELETE_REQUEST = "PARVARIK_NIRDIKISHA_DELETE_REQUEST";
export const PARVARIK_NIRDIKISHA_DELETE_SUCCESS = "PARVARIK_NIRDIKISHA_DELETE_SUCCESS";
export const PARVARIK_NIRDIKISHA_DELETE_FAIL = "PARVARIK_NIRDIKISHA_DELETE_FAIL";

export const PARVARIK_NIRDIKISHA_CLEAR_ERROR = "PARVARIK_NIRDIKISHA_CLEAR_ERROR";
