export const SAGAYI_SAPAN_GET_REQUEST = "SAGAYI_SAPAN_GET_REQUEST";
export const SAGAYI_SAPAN_GET_SUCCESS = "SAGAYI_SAPAN_GET_SUCCESS";
export const SAGAYI_SAPAN_GET_FAIL = "SAGAYI_SAPAN_GET_FAIL";

export const SAGAYI_SAPAN_CREATE_REQUEST = "SAGAYI_SAPAN_CREATE_REQUEST";
export const SAGAYI_SAPAN_CREATE_SUCCESS = "SAGAYI_SAPAN_CREATE_SUCCESS";
export const SAGAYI_SAPAN_CREATE_FAIL = "SAGAYI_SAPAN_CREATE_FAIL";

export const SAGAYI_SAPAN_UPDATE_REQUEST = "SAGAYI_SAPAN_UPDATE_REQUEST";
export const SAGAYI_SAPAN_UPDATE_SUCCESS = "SAGAYI_SAPAN_UPDATE_SUCCESS";
export const SAGAYI_SAPAN_UPDATE_FAIL = "SAGAYI_SAPAN_UPDATE_FAIL";

export const SAGAYI_SAPAN_DELETE_REQUEST = "SAGAYI_SAPAN_DELETE_REQUEST";
export const SAGAYI_SAPAN_DELETE_SUCCESS = "SAGAYI_SAPAN_DELETE_SUCCESS";
export const SAGAYI_SAPAN_DELETE_FAIL = "SAGAYI_SAPAN_DELETE_FAIL";

export const SAGAYI_SAPAN_CLEAR_ERROR = "SAGAYI_SAPAN_CLEAR_ERROR";
