export const SAMAJIK_SEVA_GET_REQUEST = "SAMAJIK_SEVA_GET_REQUEST";
export const SAMAJIK_SEVA_GET_SUCCESS = "SAMAJIK_SEVA_GET_SUCCESS";
export const SAMAJIK_SEVA_GET_FAIL = "SAMAJIK_SEVA_GET_FAIL";

export const SAMAJIK_SEVA_CREATE_REQUEST = "SAMAJIK_SEVA_CREATE_REQUEST";
export const SAMAJIK_SEVA_CREATE_SUCCESS = "SAMAJIK_SEVA_CREATE_SUCCESS";
export const SAMAJIK_SEVA_CREATE_FAIL = "SAMAJIK_SEVA_CREATE_FAIL";

export const SAMAJIK_SEVA_UPDATE_REQUEST = "SAMAJIK_SEVA_UPDATE_REQUEST";
export const SAMAJIK_SEVA_UPDATE_SUCCESS = "SAMAJIK_SEVA_UPDATE_SUCCESS";
export const SAMAJIK_SEVA_UPDATE_FAIL = "SAMAJIK_SEVA_UPDATE_FAIL";

export const SAMAJIK_SEVA_DELETE_REQUEST = "SAMAJIK_SEVA_DELETE_REQUEST";
export const SAMAJIK_SEVA_DELETE_SUCCESS = "SAMAJIK_SEVA_DELETE_SUCCESS";
export const SAMAJIK_SEVA_DELETE_FAIL = "SAMAJIK_SEVA_DELETE_FAIL";

export const SAMAJIK_SEVA_CLEAR_ERRORS = "SAMAJIK_SEVA_CLEAR_ERRORS";