export const SAMAJIK_SEVAYEIN_GET_REQUEST = "SAMAJIK_SEVAYEIN_GET_REQUEST";
export const SAMAJIK_SEVAYEIN_GET_SUCCESS = "SAMAJIK_SEVAYEIN_GET_SUCCESS";
export const SAMAJIK_SEVAYEIN_GET_FAIL = "SAMAJIK_SEVAYEIN_GET_FAIL";

export const SAMAJIK_SEVAYEIN_CREATE_REQUEST =
  "SAMAJIK_SEVAYEIN_CREATE_REQUEST";
export const SAMAJIK_SEVAYEIN_CREATE_SUCCESS =
  "SAMAJIK_SEVAYEIN_CREATE_SUCCESS";
export const SAMAJIK_SEVAYEIN_CREATE_FAIL = "SAMAJIK_SEVAYEIN_CREATE_FAIL";

export const SAMAJIK_SEVAYEIN_UPDATE_REQUEST =
  "SAMAJIK_SEVAYEIN_UPDATE_REQUEST";
export const SAMAJIK_SEVAYEIN_UPDATE_SUCCESS =
  "SAMAJIK_SEVAYEIN_UPDATE_SUCCESS";
export const SAMAJIK_SEVAYEIN_UPDATE_FAIL = "SAMAJIK_SEVAYEIN_UPDATE_FAIL";

export const SAMAJIK_SEVAYEIN_DELETE_REQUEST =
  "SAMAJIK_SEVAYEIN_DELETE_REQUEST";
export const SAMAJIK_SEVAYEIN_DELETE_SUCCESS =
  "SAMAJIK_SEVAYEIN_DELETE_SUCCESS";
export const SAMAJIK_SEVAYEIN_DELETE_FAIL = "SAMAJIK_SEVAYEIN_DELETE_FAIL";

export const SAMAJIK_SEVAYEIN_CLEAR_ERRORS = "SAMAJIK_SEVAYEIN_CLEAR_ERRORS";
