export const SAMAJIKSANSTHAYE_GET_REQUEST = "SAMAJIKSANSTHAYE_GET_REQUEST";
export const SAMAJIKSANSTHAYE_GET_SUCCESS = "SAMAJIKSANSTHAYE_GET_SUCCESS";
export const SAMAJIKSANSTHAYE_GET_FAIL = "SAMAJIKSANSTHAYE_GET_FAIL";

export const SAMAJIKSANSTHAYE_CREATE_REQUEST = "SAMAJIKSANSTHAYE_CREATE_REQUEST";
export const SAMAJIKSANSTHAYE_CREATE_SUCCESS = "SAMAJIKSANSTHAYE_CREATE_SUCCESS";
export const SAMAJIKSANSTHAYE_CREATE_FAIL = "SAMAJIKSANSTHAYE_CREATE_FAIL";

export const SAMAJIKSANSTHAYE_UPDATE_REQUEST = "SAMAJIKSANSTHAYE_UPDATE_REQUEST";
export const SAMAJIKSANSTHAYE_UPDATE_SUCCESS = "SAMAJIKSANSTHAYE_UPDATE_SUCCESS";
export const SAMAJIKSANSTHAYE_UPDATE_FAIL = "SAMAJIKSANSTHAYE_UPDATE_FAIL";

export const SAMAJIKSANSTHAYE_DELETE_REQUEST = "SAMAJIKSANSTHAYE_DELETE_REQUEST";
export const SAMAJIKSANSTHAYE_DELETE_SUCCESS = "SAMAJIKSANSTHAYE_DELETE_SUCCESS";
export const SAMAJIKSANSTHAYE_DELETE_FAIL = "SAMAJIKSANSTHAYE_DELETE_FAIL";

export const SAMAJIKSANSTHAYE_CLEAR_ERROR = "SAMAJIKSANSTHAYE_CLEAR_ERROR";
