export const SAMAJKEGAURAV_GET_REQUEST = "SAMAJKEGAURAV_GET_REQUEST";
export const SAMAJKEGAURAV_GET_SUCCESS = "SAMAJKEGAURAV_GET_SUCCESS";
export const SAMAJKEGAURAV_GET_FAIL = "SAMAJKEGAURAV_GET_FAIL";

export const SAMAJKEGAURAV_CREATE_REQUEST = "SAMAJKEGAURAV_CREATE_REQUEST";
export const SAMAJKEGAURAV_CREATE_SUCCESS = "SAMAJKEGAURAV_CREATE_SUCCESS";
export const SAMAJKEGAURAV_CREATE_FAIL = "SAMAJKEGAURAV_CREATE_FAIL";

export const SAMAJKEGAURAV_UPDATE_REQUEST = "SAMAJKEGAURAV_UPDATE_REQUEST";
export const SAMAJKEGAURAV_UPDATE_SUCCESS = "SAMAJKEGAURAV_UPDATE_SUCCESS";
export const SAMAJKEGAURAV_UPDATE_FAIL = "SAMAJKEGAURAV_UPDATE_FAIL";

export const SAMAJKEGAURAV_DELETE_REQUEST = "SAMAJKEGAURAV_DELETE_REQUEST";
export const SAMAJKEGAURAV_DELETE_SUCCESS = "SAMAJKEGAURAV_DELETE_SUCCESS";
export const SAMAJKEGAURAV_DELETE_FAIL = "SAMAJKEGAURAV_DELETE_FAIL";

export const SAMAJKEGAURAV_CLEAR_ERROR = "SAMAJKEGAURAV_CLEAR_ERROR";
